CC=gcc
FLAGS= -Wall -g

all: stringProg

stringProg: Strings.o main.o
	$(CC) $(FLAGS) -o stringProg Strings.o main.o

main.o: main.c Strings.h
	$(CC) $(FLAGS) -c main.c

String.o: Strings.c Strings.h
	$(CC) $(FLAGS) -c Strings.c
